services:
  nuxt-app:
    restart: 'no'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.chrispaganon-${APP_ENV}-router.rule=Host(`${APP_HOST}`)'
      - 'traefik.http.routers.chrispaganon-${APP_ENV}-router.entrypoints=web'
      - 'traefik.http.routers.chrispaganon-${APP_ENV}-router.tls=false'
